-- =====================================================================
-- Chasing Excellence Scorecards — 03 SEED: Life Balance  (PROPOSAL, NOT YET RUN)
--
-- Ported verbatim from life-balance-scorecard-prototype.html:
--   8 categories, 241 library items, 53 flagged is_default_on.
--   Labels, order and default frequencies are exactly the prototype's.
--
-- Idempotent. `code` (a slug of the original label) is the conflict key,
-- so fixing a typo in `label` later updates the row instead of orphaning
-- every user_scorecard_item that points at it.
--
-- NOT seeded: target months for quarterly/semiannual/annual items. The
-- app assigns sc_user_scorecard_items.target_month when the user selects
-- one, spreading them across the year (spec 4). Left null here on purpose.
-- =====================================================================

insert into public.sc_templates
  (slug, name, description, score_label, scoring_mode,
   allows_multi_instance, is_published, access_tier, sort_order)
values
  ('life-balance', 'Life Balance Scorecard',
   'Rate yourself across the areas that make a whole life. The goal is a round shape, not a perfect score.',
   'Balance', 'binary', false, true, 'free', 0)
on conflict (slug) do update set
  name = excluded.name, description = excluded.description,
  score_label = excluded.score_label, scoring_mode = excluded.scoring_mode,
  allows_multi_instance = excluded.allows_multi_instance,
  is_published = excluded.is_published, access_tier = excluded.access_tier,
  sort_order = excluded.sort_order, updated_at = now();

insert into public.sc_categories (template_id, code, name, sort_order)
select t.id, v.code, v.name, v.sort_order
from public.sc_templates t
cross join (values
  ('faith', 'Faith', 0),
  ('spouse', 'Family: Spouse', 1),
  ('family', 'Family', 2),
  ('friends', 'Friends', 3),
  ('health', 'Health', 4),
  ('self', 'Self', 5),
  ('wealth', 'Wealth', 6),
  ('work', 'Work', 7)
) as v(code, name, sort_order)
where t.slug = 'life-balance'
on conflict (template_id, code) do update set
  name = excluded.name, sort_order = excluded.sort_order, updated_at = now();

-- ---------------------------------------------------------------------
-- 241 library items
-- ---------------------------------------------------------------------
insert into public.sc_library_items
  (category_id, code, label, default_frequency, is_default_on, sort_order)
select c.id, v.code, v.label, v.freq::sc_frequency, v.is_default_on, v.sort_order
from public.sc_categories c
join public.sc_templates t on t.id = c.template_id and t.slug = 'life-balance'
join (values
  -- Faith (27 items, 6 on by default)
  ('faith', 'daily-devotional', 'Daily Devotional', 'daily', false, 0),
  ('faith', 'gratitude-journal', 'Gratitude Journal', 'daily', true, 1),
  ('faith', 'nightly-prayers-with-kids', 'Nightly Prayers with Kids', 'daily', false, 2),
  ('faith', 'pray', 'Pray', 'daily', true, 3),
  ('faith', 'read-the-bible-5-min', 'Read the Bible (5 min)', 'daily', true, 4),
  ('faith', 'volunteer-at-church', 'Volunteer at Church', 'daily', false, 5),
  ('faith', 'attend-bible-study', 'Attend Bible Study', 'weekly', false, 6),
  ('faith', 'attend-church', 'Attend Church', 'weekly', true, 7),
  ('faith', 'have-a-faith-mentor', 'Have a Faith Mentor', 'weekly', false, 8),
  ('faith', 'invite-someone-to-church', 'Invite Someone to Church', 'weekly', false, 9),
  ('faith', 'read-15-min-on-other-religions', 'Read 15 min on Other Religions', 'weekly', false, 10),
  ('faith', 'serve-someone-anonymously', 'Serve Someone Anonymously', 'weekly', false, 11),
  ('faith', 'memorize-a-verse-or-passage', 'Memorize a Verse or Passage', 'weekly', false, 12),
  ('faith', 'attend-church-on-holy-days', 'Attend Church on Holy Days', 'monthly', false, 13),
  ('faith', 'practice-religious-rituals', 'Practice Religious Rituals', 'monthly', false, 14),
  ('faith', 'tithe-10pct-of-income', 'Tithe 10% of Income', 'monthly', true, 15),
  ('faith', 'volunteer-on-church-committee', 'Volunteer on Church Committee', 'monthly', false, 16),
  ('faith', 'mentor-someone-in-faith', 'Mentor Someone in Faith', 'monthly', false, 17),
  ('faith', 'community-service-1-hour', 'Community Service (1 hour)', 'quarterly', true, 18),
  ('faith', 'attend-church-retreat', 'Attend Church Retreat', 'annual', false, 19),
  ('faith', 'attend-mission-trip', 'Attend Mission Trip', 'annual', false, 20),
  ('faith', 'pray-for-someone-by-name', 'Pray for Someone by Name', 'daily', false, 21),
  ('faith', 'worship-music', 'Worship Music', 'daily', false, 22),
  ('faith', 'attend-a-small-group', 'Attend a Small Group', 'weekly', false, 23),
  ('faith', 'confession-or-examine-conscience', 'Confession or Examine Conscience', 'monthly', false, 24),
  ('faith', 'give-to-a-cause-outside-church', 'Give to a Cause Outside Church', 'monthly', false, 25),
  ('faith', 'faith-conversation-with-a-skeptic', 'Faith Conversation with a Skeptic', 'monthly', false, 26),
  -- Family: Spouse (31 items, 7 on by default)
  ('spouse', 'hugs-and-kisses-7-seconds', 'Hugs & Kisses (7 seconds)', 'daily', true, 0),
  ('spouse', 'kind-words', 'Kind Words', 'daily', true, 1),
  ('spouse', 'quality-time-10-min', 'Quality Time (10 min)', 'daily', true, 2),
  ('spouse', 'open-honest-don-t-go-to-bed-mad', 'Open, Honest — Don''t Go to Bed Mad', 'daily', false, 3),
  ('spouse', 'ask-about-their-day-and-listen', 'Ask About Their Day and Listen', 'daily', false, 4),
  ('spouse', 'pray-together', 'Pray Together', 'daily', false, 5),
  ('spouse', 'compliment-spouse', 'Compliment Spouse', 'weekly', true, 6),
  ('spouse', 'help-spouse-with-chores', 'Help Spouse with Chores', 'weekly', false, 7),
  ('spouse', 'lunch-together', 'Lunch Together', 'weekly', false, 8),
  ('spouse', 'intimacy', 'Intimacy', 'weekly', false, 9),
  ('spouse', 'phone-free-evening-together', 'Phone-Free Evening Together', 'weekly', false, 10),
  ('spouse', 'date-night', 'Date Night', 'monthly', true, 11),
  ('spouse', 'mutual-hobby-together', 'Mutual Hobby Together', 'monthly', false, 12),
  ('spouse', 'random-gift', 'Random Gift', 'monthly', false, 13),
  ('spouse', 'review-disc-and-enneagram', 'Review DISC & Enneagram', 'monthly', false, 14),
  ('spouse', 'review-budget-together', 'Review Budget Together', 'monthly', false, 15),
  ('spouse', 'review-five-qualities', 'Review Five Qualities', 'monthly', false, 16),
  ('spouse', 'review-love-languages', 'Review Love Languages', 'monthly', false, 17),
  ('spouse', 'book-club-together', 'Book Club Together', 'monthly', false, 18),
  ('spouse', 'couples-therapy', 'Couples Therapy', 'monthly', false, 19),
  ('spouse', 'date-night-with-another-couple', 'Date Night with Another Couple', 'monthly', false, 20),
  ('spouse', 'big-surprise-or-gesture', 'Big Surprise or Gesture', 'quarterly', false, 21),
  ('spouse', 'discuss-1-3-5-10-year-letters', 'Discuss 1, 3, 5, 10 Year Letters', 'quarterly', false, 22),
  ('spouse', 'plan-the-next-trip-together', 'Plan the Next Trip Together', 'quarterly', false, 23),
  ('spouse', 'couples-trip', 'Couples Trip', 'annual', true, 24),
  ('spouse', 'say-thank-you-for-something-specific', 'Say Thank You for Something Specific', 'daily', true, 25),
  ('spouse', 'share-a-win-from-the-day', 'Share a Win from the Day', 'daily', false, 26),
  ('spouse', 'weekly-marriage-check-in', 'Weekly Marriage Check-In', 'weekly', false, 27),
  ('spouse', 'serve-them-without-being-asked', 'Serve Them Without Being Asked', 'weekly', false, 28),
  ('spouse', 'write-a-note-or-card', 'Write a Note or Card', 'monthly', false, 29),
  ('spouse', 'marriage-book-or-course', 'Marriage Book or Course', 'quarterly', false, 30),
  -- Family (34 items, 7 on by default)
  ('family', 'hugs-and-kisses', 'Hugs & Kisses', 'daily', true, 0),
  ('family', 'open-honest-apologize', 'Open, Honest, Apologize', 'daily', false, 1),
  ('family', 'tell-kids-you-love-them', 'Tell Kids You Love Them', 'daily', true, 2),
  ('family', 'read-to-kids', 'Read to Kids', 'daily', false, 3),
  ('family', 'call-family-dad-mom-siblings', 'Call Family (Dad, Mom, Siblings)', 'weekly', true, 4),
  ('family', 'family-activity', 'Family Activity', 'weekly', true, 5),
  ('family', 'family-breakfast-3x', 'Family Breakfast (3x)', 'weekly', false, 6),
  ('family', 'family-dinner-2x', 'Family Dinner (2x)', 'weekly', true, 7),
  ('family', 'review-finances-with-kids', 'Review Finances with Kids', 'weekly', false, 8),
  ('family', 'school-or-camp-pickup', 'School or Camp Pickup', 'weekly', false, 9),
  ('family', '10-hours-family-focused-time', '10 Hours Family-Focused Time', 'weekly', false, 10),
  ('family', 'family-meeting', 'Family Meeting', 'weekly', false, 11),
  ('family', 'attend-school-and-sports-events', 'Attend School & Sports Events', 'monthly', true, 12),
  ('family', 'daddy-daughter-date', 'Daddy Daughter Date', 'monthly', false, 13),
  ('family', 'one-on-one-with-each-kid', 'One-on-One with Each Kid', 'monthly', false, 14),
  ('family', 'know-disc-and-enneagram', 'Know DISC & Enneagram', 'monthly', false, 15),
  ('family', 'power-numbers', 'Power Numbers', 'monthly', false, 16),
  ('family', 'review-family-vision-board', 'Review Family Vision Board', 'monthly', false, 17),
  ('family', 'vip-pyramid', 'VIP Pyramid', 'monthly', false, 18),
  ('family', 'visit-family', 'Visit Family', 'monthly', false, 19),
  ('family', 'save-a-photo-or-video-memory', 'Save a Photo or Video Memory', 'monthly', false, 20),
  ('family', 'big-surprise-or-gesture', 'Big Surprise or Gesture', 'quarterly', false, 21),
  ('family', 'discuss-1-3-5-10-year-letters', 'Discuss 1, 3, 5, 10 Year Letters', 'quarterly', false, 22),
  ('family', 'review-family-bucket-list', 'Review Family Bucket List', 'quarterly', false, 23),
  ('family', 'review-qualities-for-future-spouse', 'Review Qualities for Future Spouse', 'quarterly', false, 24),
  ('family', 'family-vacation', 'Family Vacation', 'annual', true, 25),
  ('family', 'eat-without-screens', 'Eat Without Screens', 'daily', false, 26),
  ('family', 'bedtime-routine', 'Bedtime Routine', 'daily', false, 27),
  ('family', 'ask-each-kid-a-real-question', 'Ask Each Kid a Real Question', 'daily', false, 28),
  ('family', 'family-prayer-or-devotional', 'Family Prayer or Devotional', 'daily', false, 29),
  ('family', 'teach-a-skill', 'Teach a Skill', 'monthly', false, 30),
  ('family', 'extended-family-gathering', 'Extended Family Gathering', 'quarterly', false, 31),
  ('family', 'volunteer-as-a-family', 'Volunteer as a Family', 'quarterly', false, 32),
  ('family', 'update-emergency-plan-and-documents', 'Update Emergency Plan and Documents', 'annual', false, 33),
  -- Friends (15 items, 5 on by default)
  ('friends', 'text-core-friends', 'Text Core Friends', 'weekly', true, 0),
  ('friends', 'call-core-friends', 'Call Core Friends', 'monthly', true, 1),
  ('friends', 'no-vampires-filter-via-power-number', 'No Vampires — Filter via Power Number', 'monthly', false, 2),
  ('friends', 'check-in-on-someone-struggling', 'Check In on Someone Struggling', 'monthly', false, 3),
  ('friends', 'host-an-event', 'Host an Event', 'quarterly', true, 4),
  ('friends', 'visit-core-friends', 'Visit Core Friends', 'quarterly', false, 5),
  ('friends', 'make-a-new-friend', 'Make a New Friend', 'quarterly', false, 6),
  ('friends', 'reconnect-with-an-old-friend', 'Reconnect with an Old Friend', 'quarterly', false, 7),
  ('friends', 'birthday-calls', 'Birthday Calls', 'annual', true, 8),
  ('friends', 'group-trip', 'Group Trip', 'annual', false, 9),
  ('friends', 'hand-written-note', 'Hand Written Note', 'annual', false, 10),
  ('friends', 'be-the-one-who-initiates', 'Be the One Who Initiates', 'weekly', true, 11),
  ('friends', 'celebrate-a-friend-win', 'Celebrate a Friend Win', 'monthly', false, 12),
  ('friends', 'invite-someone-to-coffee-or-lunch', 'Invite Someone to Coffee or Lunch', 'monthly', false, 13),
  ('friends', 'show-up-in-person-when-it-matters', 'Show Up in Person When It Matters', 'quarterly', false, 14),
  -- Health (34 items, 8 on by default)
  ('health', 'sleep-7-hours', 'Sleep 7 Hours', 'daily', true, 0),
  ('health', 'no-snooze', 'No Snooze', 'daily', false, 1),
  ('health', 'pink-drink', 'Pink Drink', 'daily', false, 2),
  ('health', 'stretch', 'Stretch', 'daily', true, 3),
  ('health', 'exercise', 'Exercise', 'daily', true, 4),
  ('health', 'steps-10k', 'Steps (10k)', 'daily', true, 5),
  ('health', 'cold-shower', 'Cold Shower', 'daily', false, 6),
  ('health', 'sunscreen', 'Sunscreen', 'daily', false, 7),
  ('health', '12-hour-fasting', '12 Hour Fasting', 'daily', false, 8),
  ('health', 'vitamins-morning', 'Vitamins: Morning', 'daily', false, 9),
  ('health', 'vitamins-lunch', 'Vitamins: Lunch', 'daily', false, 10),
  ('health', 'vitamins-night', 'Vitamins: Night', 'daily', false, 11),
  ('health', 'portion-control', 'Portion Control', 'daily', false, 12),
  ('health', 'eat-healthy', 'Eat Healthy', 'daily', true, 13),
  ('health', 'no-eating-3-hours-before-bed', 'No Eating 3 Hours Before Bed', 'daily', false, 14),
  ('health', 'water-100-oz', 'Water (100 oz)', 'daily', true, 15),
  ('health', 'no-tv', 'No TV', 'daily', false, 16),
  ('health', 'strength-training-3x', 'Strength Training (3x)', 'weekly', false, 17),
  ('health', 'scheduled-alcohol', 'Scheduled Alcohol', 'weekly', true, 18),
  ('health', 'chiropractor', 'Chiropractor', 'quarterly', false, 19),
  ('health', 'dentist', 'Dentist', 'semiannual', false, 20),
  ('health', 'annual-physical', 'Annual Physical', 'annual', true, 21),
  ('health', 'blood-work', 'Blood Work', 'annual', false, 22),
  ('health', 'skin-check', 'Skin Check', 'annual', false, 23),
  ('health', 'eye-exam', 'Eye Exam', 'annual', false, 24),
  ('health', 'protein-target', 'Protein Target', 'daily', false, 25),
  ('health', 'consistent-wake-time', 'Consistent Wake Time', 'daily', false, 26),
  ('health', 'no-screens-30-min-before-bed', 'No Screens 30 Min Before Bed', 'daily', false, 27),
  ('health', 'track-weight', 'Track Weight', 'weekly', false, 28),
  ('health', 'meal-prep', 'Meal Prep', 'weekly', false, 29),
  ('health', 'active-recovery-walk', 'Active Recovery Walk', 'weekly', false, 30),
  ('health', 'mobility-work', 'Mobility Work', 'weekly', false, 31),
  ('health', 'sauna-or-sweat', 'Sauna or Sweat', 'weekly', false, 32),
  ('health', 'review-bloodwork-with-doctor', 'Review Bloodwork with Doctor', 'annual', false, 33),
  -- Self (30 items, 6 on by default)
  ('self', 'meditate-5-min', 'Meditate (5 min)', 'daily', true, 0),
  ('self', 'breathing-exercise', 'Breathing Exercise', 'daily', false, 1),
  ('self', 'daily-affirmations', 'Daily Affirmations', 'daily', false, 2),
  ('self', 'journal', 'Journal', 'daily', true, 3),
  ('self', 'read-15-min', 'Read (15 min)', 'daily', true, 4),
  ('self', 'audio-book-15-min', 'Audio Book (15 min)', 'daily', false, 5),
  ('self', 'positive-thoughts', 'Positive Thoughts', 'daily', false, 6),
  ('self', 'no-phone-first-hour', 'No Phone First Hour', 'daily', false, 7),
  ('self', 'spanish-15-min', 'Spanish (15 min)', 'daily', false, 8),
  ('self', 'guitar-15-min', 'Guitar (15 min)', 'daily', false, 9),
  ('self', 'podcast', 'Podcast', 'weekly', true, 10),
  ('self', 'time-outdoors', 'Time Outdoors', 'weekly', false, 11),
  ('self', 'learn-something-new', 'Learn Something New', 'weekly', false, 12),
  ('self', 'digital-sabbath', 'Digital Sabbath', 'monthly', false, 13),
  ('self', 'therapy-or-counseling', 'Therapy or Counseling', 'monthly', false, 14),
  ('self', 'review-1-3-5-10-year-goals', 'Review 1, 3, 5, 10 Year Goals', 'monthly', true, 15),
  ('self', 'review-bucket-list', 'Review Bucket List', 'quarterly', false, 16),
  ('self', 'review-personal-vision', 'Review Personal Vision', 'quarterly', false, 17),
  ('self', 'me-day', '"Me" Day', 'quarterly', false, 18),
  ('self', 'six-weeks-of-vacation', 'Six Weeks of Vacation', 'annual', false, 19),
  ('self', 'misogi', 'Misogi', 'annual', false, 20),
  ('self', 'gratitude-three-things', 'Gratitude: Three Things', 'daily', true, 21),
  ('self', 'single-tasking-block', 'Single-Tasking Block', 'daily', false, 22),
  ('self', 'say-no-to-one-thing', 'Say No to One Thing', 'weekly', false, 23),
  ('self', 'creative-time', 'Creative Time', 'weekly', false, 24),
  ('self', 'solo-reflection-walk', 'Solo Reflection Walk', 'weekly', false, 25),
  ('self', 'unplugged-half-day', 'Unplugged Half-Day', 'monthly', false, 26),
  ('self', 'review-what-drained-you', 'Review What Drained You', 'monthly', false, 27),
  ('self', 'take-a-class-or-course', 'Take a Class or Course', 'quarterly', false, 28),
  ('self', 'personal-retreat-day', 'Personal Retreat Day', 'annual', false, 29),
  -- Wealth (31 items, 7 on by default)
  ('wealth', 'finances-daily-30-min', 'Finances Daily (30 min)', 'daily', false, 0),
  ('wealth', 'kids-allowance', 'Kids Allowance', 'weekly', false, 1),
  ('wealth', 'personal-commissions', 'Personal Commissions', 'monthly', false, 2),
  ('wealth', 'personal-budget', 'Personal Budget', 'monthly', true, 3),
  ('wealth', 'net-worth-update', 'Net Worth Update', 'monthly', false, 4),
  ('wealth', 'know-sms-numbers', 'Know SMS Numbers', 'monthly', false, 5),
  ('wealth', 'know-3r-magic-numbers', 'Know 3R Magic Numbers', 'monthly', false, 6),
  ('wealth', 'profit-and-loss', 'Profit & Loss', 'monthly', true, 7),
  ('wealth', 'business-expenses', 'Business Expenses', 'monthly', false, 8),
  ('wealth', 'investments-and-401k', 'Investments & 401k', 'monthly', true, 9),
  ('wealth', 'call-financial-advisor', 'Call Financial Advisor', 'monthly', false, 10),
  ('wealth', 'max-retirement', 'Max Retirement', 'monthly', false, 11),
  ('wealth', 'no-revolving-debt', 'No Revolving Debt', 'monthly', true, 12),
  ('wealth', 'safety-savings', 'Safety Savings', 'monthly', false, 13),
  ('wealth', 'save-25pct', 'Save 25%', 'monthly', true, 14),
  ('wealth', 'savings-for-milestones', 'Savings for Milestones', 'monthly', false, 15),
  ('wealth', 'charitable-giving', 'Charitable Giving', 'monthly', false, 16),
  ('wealth', 'review-credit-report', 'Review Credit Report', 'semiannual', true, 17),
  ('wealth', 'shop-services', 'Shop Services', 'annual', false, 18),
  ('wealth', 'insurance-review', 'Insurance Review', 'annual', false, 19),
  ('wealth', 'tax-planning-meeting', 'Tax Planning Meeting', 'annual', false, 20),
  ('wealth', 'review-wills-and-trusts', 'Review Wills & Trusts', 'annual', false, 21),
  ('wealth', 'no-unplanned-purchases', 'No Unplanned Purchases', 'daily', false, 22),
  ('wealth', 'track-every-expense', 'Track Every Expense', 'weekly', false, 23),
  ('wealth', 'emergency-fund-check', 'Emergency Fund Check', 'monthly', true, 24),
  ('wealth', 'kids-college-529', 'Kids College / 529', 'monthly', false, 25),
  ('wealth', 'teach-kids-one-money-lesson', 'Teach Kids One Money Lesson', 'monthly', false, 26),
  ('wealth', 'review-subscriptions', 'Review Subscriptions', 'quarterly', false, 27),
  ('wealth', 'rebalance-portfolio', 'Rebalance Portfolio', 'semiannual', false, 28),
  ('wealth', 'beneficiaries-current', 'Beneficiaries Current', 'annual', false, 29),
  ('wealth', 'estate-docs-reviewed-with-spouse', 'Estate Docs Reviewed with Spouse', 'annual', false, 30),
  -- Work (39 items, 7 on by default)
  ('work', 'full-gtx', 'Full GTX', 'daily', false, 0),
  ('work', 'calendar-written-no-white-space', 'Calendar Written, No White Space', 'daily', true, 1),
  ('work', 'calendar-accuracy-90pctplus', 'Calendar Accuracy 90%+', 'daily', false, 2),
  ('work', 'time-block-tomorrow', 'Time Block Tomorrow', 'daily', false, 3),
  ('work', 'social-post', 'Social: Post', 'daily', true, 4),
  ('work', 'social-comment-25x4', 'Social: Comment (25x4)', 'daily', false, 5),
  ('work', 'social-dm-25x4', 'Social: DM (25x4)', 'daily', false, 6),
  ('work', 'database-touches-10', 'Database Touches (10)', 'daily', true, 7),
  ('work', 'journal-for-business', 'Journal for Business', 'daily', false, 8),
  ('work', 'mbs-highway', 'MBS Highway', 'daily', false, 9),
  ('work', 'read-chrisman-nrep', 'Read Chrisman / NREP', 'daily', false, 10),
  ('work', 'time-green-20-hrs', 'Time: Green = 20 hrs', 'weekly', false, 11),
  ('work', 'time-gold-5-hrs', 'Time: Gold = 5 hrs', 'weekly', false, 12),
  ('work', 'time-recruiting-10-hrs', 'Time: Recruiting = 10 hrs', 'weekly', false, 13),
  ('work', 'time-on-business-2-hrs', 'Time: On Business = 2 hrs', 'weekly', false, 14),
  ('work', 'time-total-50-hrs', 'Time: Total = 50 hrs', 'weekly', false, 15),
  ('work', 'weekly-business-review', 'Weekly Business Review', 'weekly', false, 16),
  ('work', 'review-pipeline', 'Review Pipeline', 'weekly', true, 17),
  ('work', 'team-one-on-ones', 'Team One-on-Ones', 'weekly', false, 18),
  ('work', 'ask-for-a-review', 'Ask for a Review', 'weekly', false, 19),
  ('work', 'thank-a-referral-partner', 'Thank a Referral Partner', 'weekly', false, 20),
  ('work', 'get-coached-2x', 'Get Coached (2x)', 'monthly', true, 21),
  ('work', 'coach-someone', 'Coach Someone', 'monthly', false, 22),
  ('work', 'read-a-business-book', 'Read a Business Book', 'monthly', false, 23),
  ('work', 'goals-vs-actuals', 'Goals vs Actuals', 'monthly', true, 24),
  ('work', 'attend-training-or-mastermind', 'Attend Training or Mastermind', 'quarterly', false, 25),
  ('work', 'top-three-priorities-written', 'Top Three Priorities Written', 'daily', true, 26),
  ('work', 'update-crm', 'Update CRM', 'daily', false, 27),
  ('work', 'follow-up-on-every-lead', 'Follow Up on Every Lead', 'daily', false, 28),
  ('work', 'inbox-to-zero', 'Inbox to Zero', 'daily', false, 29),
  ('work', 'call-past-clients-5', 'Call Past Clients (5)', 'weekly', false, 30),
  ('work', 'preapproval-follow-ups', 'Preapproval Follow-Ups', 'weekly', false, 31),
  ('work', 'video-message-to-a-partner', 'Video Message to a Partner', 'weekly', false, 32),
  ('work', 'take-a-full-day-off', 'Take a Full Day Off', 'weekly', false, 33),
  ('work', 'review-lost-deals', 'Review Lost Deals', 'monthly', false, 34),
  ('work', 'personal-p-and-l-for-business', 'Personal P and L for Business', 'monthly', false, 35),
  ('work', 'quarterly-rocks-set', 'Quarterly Rocks Set', 'quarterly', false, 36),
  ('work', 'update-marketing-plan', 'Update Marketing Plan', 'quarterly', false, 37),
  ('work', 'annual-business-plan', 'Annual Business Plan', 'annual', false, 38)
) as v(cat, code, label, freq, is_default_on, sort_order) on v.cat = c.code
on conflict (category_id, code) do update set
  label = excluded.label,
  default_frequency = excluded.default_frequency,
  is_default_on = excluded.is_default_on,
  sort_order = excluded.sort_order,
  is_active = true,
  updated_at = now();

-- ---------------------------------------------------------------------
-- Verify: expect 8 categories / 241 items / 53 defaults
-- ---------------------------------------------------------------------
select c.code, c.name, count(*) as items,
       count(*) filter (where i.is_default_on) as defaults
from public.sc_categories c
join public.sc_templates t on t.id = c.template_id and t.slug = 'life-balance'
left join public.sc_library_items i on i.category_id = c.id
group by c.code, c.name, c.sort_order
order by c.sort_order;
